/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.test_dgt;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.awt.print.Book;
import java.io.File;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author valde
 */
public class FRAME_test extends javax.swing.JFrame {
    
    PANEL_Principal panelPrincipal;
    PANEL_Preguntas panelPreguntas = new PANEL_Preguntas();
    
    public FRAME_test() {
        initComponents();
        panelPrincipal = new PANEL_Principal();
        panelPrincipal.setVisible(true);
        panelControlador.add(panelPrincipal);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnTest = new javax.swing.JButton();
        lblAvisoIniciarTest = new javax.swing.JLabel();
        panelControlador = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        jMenuEdicion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTest.setText("INICIAR TEST");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        lblAvisoIniciarTest.setForeground(new java.awt.Color(255, 0, 0));

        panelControlador.setLayout(new java.awt.GridBagLayout());

        jMenuEdicion.setText("Edición...");
        menuBar.add(jMenuEdicion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAvisoIniciarTest, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(btnTest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(panelControlador, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelControlador, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAvisoIniciarTest, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnTest)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        if(btnTest.getText().equals("INICIAR TEST")){
            if(!panelPrincipal.comprobarContenidoCampos()){

                panelPrincipal.setVisible(false);
                btnTest.setText("FINALIZAR TEST");
                panelPrincipal = null;
                panelControlador.add(panelPreguntas);

                try {
                    // create object mapper instance
                    ObjectMapper mapper = new ObjectMapper();

                    // convert JSON array to list of books
                    File file = new File("AM.json");
                    final ObjectMapper objectMapper = new ObjectMapper();
                    List<Pregunta> langList = objectMapper.readValue(
                        file,
                        new TypeReference<List<Pregunta>>(){});

                    ArrayList<Pregunta> lista = new ArrayList();
                    langList.forEach(x -> lista.add(x));

                    panelPreguntas.almacenarPreguntas(lista);
                    panelPreguntas.dividirCadenasLargasArrayList();
                    panelPreguntas.mostrarPrimeraPregunta();

                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            }else{
                lblAvisoIniciarTest.setText("Se deben de rellenar todos datos personales");
                lblAvisoIniciarTest.setVisible(true);
            }
        }
        else if(btnTest.getText().equals("FINALIZAR TEST")){

        }
    }//GEN-LAST:event_btnTestActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRAME_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRAME_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRAME_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRAME_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRAME_test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTest;
    private javax.swing.JMenu jMenuEdicion;
    private javax.swing.JLabel lblAvisoIniciarTest;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelControlador;
    // End of variables declaration//GEN-END:variables
}
