/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marcovalderrey.mycompany.test_dgt;

import java.io.Serializable;

/**
 *
 * @author valde
 */
public class BEAN_Opciones_Preguntas extends javax.swing.JPanel implements Serializable{

    boolean opcionA = false;
    boolean opcionB = false;
    boolean opcionC = false;
    boolean opcionD = false;
    
    /**
     * Creates new form BEAN_Opciones_Preguntas
     */
    public BEAN_Opciones_Preguntas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpcionA = new javax.swing.JToggleButton();
        btnOpcionB = new javax.swing.JToggleButton();
        btnOpcionC = new javax.swing.JToggleButton();
        btnOpcionD = new javax.swing.JToggleButton();

        btnOpcionA.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnOpcionA.setText("A");
        btnOpcionA.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnOpcionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionAActionPerformed(evt);
            }
        });

        btnOpcionB.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnOpcionB.setText("B");
        btnOpcionB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnOpcionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionBActionPerformed(evt);
            }
        });

        btnOpcionC.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnOpcionC.setText("C");
        btnOpcionC.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnOpcionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionCActionPerformed(evt);
            }
        });

        btnOpcionD.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnOpcionD.setText("D");
        btnOpcionD.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnOpcionD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnOpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnOpcionD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnOpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOpcionD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionAActionPerformed
        pulsarBoton("A", opcionA);
    }//GEN-LAST:event_btnOpcionAActionPerformed

    private void btnOpcionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionBActionPerformed
        pulsarBoton("B", opcionB);
    }//GEN-LAST:event_btnOpcionBActionPerformed

    private void btnOpcionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionCActionPerformed
        pulsarBoton("C", opcionC);
    }//GEN-LAST:event_btnOpcionCActionPerformed

    private void btnOpcionDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionDActionPerformed
        pulsarBoton("D", opcionD);
    }//GEN-LAST:event_btnOpcionDActionPerformed

    public void pulsarBoton(String opcion, boolean estado){
    
        if(!estado){
            
            opcionA = false;
            opcionB = false;
            opcionC = false;
            opcionD = false;
            
            btnOpcionA.setEnabled(true);
            btnOpcionB.setEnabled(true);
            btnOpcionC.setEnabled(true);
            btnOpcionD.setEnabled(true);
            
            btnOpcionA.setSelected(false);
            btnOpcionB.setSelected(false);
            btnOpcionC.setSelected(false);
            btnOpcionD.setSelected(false);
            
            switch(opcion){
                case "A":
                    opcionA = true;
                    btnOpcionA.setEnabled(false);
                break;
                case "B":
                    opcionB = true;
                    btnOpcionB.setEnabled(false);
                break;
                case "C":
                    opcionC = true;
                    btnOpcionC.setEnabled(false);
                break;
                case "D":
                    opcionD = true;
                    btnOpcionD.setEnabled(false);
                break;
            }
            
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnOpcionA;
    private javax.swing.JToggleButton btnOpcionB;
    private javax.swing.JToggleButton btnOpcionC;
    private javax.swing.JToggleButton btnOpcionD;
    // End of variables declaration//GEN-END:variables
}
