/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marcovalderrey.mycompany.test_dgt;

import java.awt.Color;
import java.io.Serializable;

/**
 *
 * @author valde
 */
public class BEAN_Informes extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form PANEL_Informes
     */
    public BEAN_Informes() {
        initComponents();
    } 

    void setNombreYApellidos(String nombreYApellidos){
        lblNombreARellenar.setText(nombreYApellidos);
    }
    void setDni(String dni){
        lblDNIARellenar.setText(dni);
    }
    void setTipoTest(String tipoTest){
        lblTipoTestARellenar.setText(tipoTest);
    }
    void setFallosMaximos(String fallosMaximos){
        lblFallosMaximosARellenar.setText(fallosMaximos);
    }
    void setPreguntasFalladas(String preguntasFalladas){
        lblPreguntasFalladasARellenar.setText(preguntasFalladas);
    }
    void setCalificacion(){
        int fallosMax = Integer.valueOf(lblFallosMaximosARellenar.getText());
        int pregFalladas = Integer.valueOf(lblPreguntasFalladasARellenar.getText());
        if(pregFalladas >= fallosMax){
            lblCalificacion.setText("SUSPENSO");
            lblCalificacion.setForeground(Color.red);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        lblFallosMaximosARellenar = new javax.swing.JLabel();
        lblPreguntasfalladas = new javax.swing.JLabel();
        lblPreguntasFalladasARellenar = new javax.swing.JLabel();
        lblCalificacion = new javax.swing.JLabel();
        lblTipoTestARellenar = new javax.swing.JLabel();
        lblNombreYApellidos = new javax.swing.JLabel();
        lblTipoTest = new javax.swing.JLabel();
        lblDNIARellenar = new javax.swing.JLabel();
        lblNombreARellenar = new javax.swing.JLabel();
        lblFallosMaximos = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        lblFallosMaximosARellenar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblFallosMaximosARellenar.setText("............................");

        lblPreguntasfalladas.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblPreguntasfalladas.setText("Preguntas falladas:");

        lblPreguntasFalladasARellenar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblPreguntasFalladasARellenar.setText("............................");

        lblCalificacion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCalificacion.setForeground(new java.awt.Color(51, 255, 51));
        lblCalificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalificacion.setText("APROBADO");

        lblTipoTestARellenar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTipoTestARellenar.setText("............................");

        lblNombreYApellidos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNombreYApellidos.setText("Nombre y apellidos: ");

        lblTipoTest.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblTipoTest.setText("Tipo de test: ");

        lblDNIARellenar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblDNIARellenar.setText("............................");

        lblNombreARellenar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblNombreARellenar.setText("..............................................................................");

        lblFallosMaximos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblFallosMaximos.setText("Fallos máximos:");

        lblDNI.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDNI.setText("DNI: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFallosMaximos)
                    .addComponent(lblFallosMaximosARellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(lblCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDNI)
                    .addComponent(lblDNIARellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreARellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreYApellidos)
                    .addComponent(lblPreguntasFalladasARellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoTest)
                    .addComponent(lblTipoTestARellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreguntasfalladas))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNombreYApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreARellenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDNIARellenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipoTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipoTestARellenar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblCalificacion))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFallosMaximos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFallosMaximosARellenar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreguntasfalladas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreguntasFalladasARellenar))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblCalificacion;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDNIARellenar;
    private javax.swing.JLabel lblFallosMaximos;
    private javax.swing.JLabel lblFallosMaximosARellenar;
    private javax.swing.JLabel lblNombreARellenar;
    private javax.swing.JLabel lblNombreYApellidos;
    private javax.swing.JLabel lblPreguntasFalladasARellenar;
    private javax.swing.JLabel lblPreguntasfalladas;
    private javax.swing.JLabel lblTipoTest;
    private javax.swing.JLabel lblTipoTestARellenar;
    // End of variables declaration//GEN-END:variables
}
