/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marcovalderrey.mycompany.test_dgt;

import java.io.Serializable;
import javax.swing.JFrame;

/**
 *
 * @author valde
 */
public class BEAN_ResultadosTest extends javax.swing.JPanel implements Serializable{

    JFrame framePrograma;
    
    /**
     * Creates new form BEAN_ResultadosTest
     */
    public BEAN_ResultadosTest() {
        initComponents();
    }

    public void setLblDNIARellenar(String lblDNIARellenar) {
        this.lblDNIARellenar.setText(lblDNIARellenar);
    }

    public void setLblNombreARellenar(String lblNombreARellenar) {
        this.lblNombreARellenar.setText(lblNombreARellenar);
    }

    public void setLblNumPreguntasARellenar(String lblNumPreguntasARellenar) {
        this.lblNumPreguntasARellenar.setText(lblNumPreguntasARellenar);
    }

    public void setLblTipoTestARellenar(String lblTipoTestARellenar) {
        this.lblTipoTestARellenar.setText(lblTipoTestARellenar);
    }

    public void setLblPreguntasContestadasARellenar(String lblPreguntasContestadasARellenar) {
        this.lblPreguntasContestadasARellenar.setText(lblPreguntasContestadasARellenar);
    }


    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreYApellidos = new javax.swing.JLabel();
        lblNombreARellenar = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        lblDNIARellenar = new javax.swing.JLabel();
        lblTipoTest = new javax.swing.JLabel();
        lblTipoTestARellenar = new javax.swing.JLabel();
        lblNumPreguntas = new javax.swing.JLabel();
        lblNumPreguntasARellenar = new javax.swing.JLabel();
        lblPreguntasContestadas = new javax.swing.JLabel();
        lblPreguntasContestadasARellenar = new javax.swing.JLabel();

        lblNombreYApellidos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblNombreYApellidos.setText("Nombre y apellidos: ");

        lblNombreARellenar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblNombreARellenar.setText("..............................................................................");

        lblDNI.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDNI.setText("DNI: ");

        lblDNIARellenar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblDNIARellenar.setText("............................");

        lblTipoTest.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTipoTest.setText("Tipo de test: ");

        lblTipoTestARellenar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblTipoTestARellenar.setText("............................");

        lblNumPreguntas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblNumPreguntas.setText("Nº de preguntas: ");

        lblNumPreguntasARellenar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblNumPreguntasARellenar.setText("............................");

        lblPreguntasContestadas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblPreguntasContestadas.setText("Preguntas contestadas: ");

        lblPreguntasContestadasARellenar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblPreguntasContestadasARellenar.setText("............................");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDNI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDNIARellenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblNombreYApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreARellenar, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblNumPreguntas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblNumPreguntasARellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblTipoTest)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTipoTestARellenar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPreguntasContestadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPreguntasContestadasARellenar)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreYApellidos)
                    .addComponent(lblNombreARellenar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI)
                    .addComponent(lblDNIARellenar))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoTest)
                    .addComponent(lblTipoTestARellenar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumPreguntas)
                    .addComponent(lblNumPreguntasARellenar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreguntasContestadas)
                    .addComponent(lblPreguntasContestadasARellenar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDNIARellenar;
    private javax.swing.JLabel lblNombreARellenar;
    private javax.swing.JLabel lblNombreYApellidos;
    private javax.swing.JLabel lblNumPreguntas;
    private javax.swing.JLabel lblNumPreguntasARellenar;
    private javax.swing.JLabel lblPreguntasContestadas;
    private javax.swing.JLabel lblPreguntasContestadasARellenar;
    private javax.swing.JLabel lblTipoTest;
    private javax.swing.JLabel lblTipoTestARellenar;
    // End of variables declaration//GEN-END:variables
}
