/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marcovalderrey.mycompany.test_dgt;

import java.awt.Color;

/**
 *
 * @author valde
 */
public class DIALOG_Administrador extends javax.swing.JDialog {

    boolean contraseñaCorrecta = false;
    
    public DIALOG_Administrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTextoBienvenida = new javax.swing.JLabel();
        txtFieldContraseña = new javax.swing.JTextField();
        btnComprobar = new javax.swing.JButton();
        lblAvisoContraseña = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblTextoBienvenida.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTextoBienvenida.setText("Introduce la contaseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(88, 156, 0, 147);
        getContentPane().add(lblTextoBienvenida, gridBagConstraints);

        txtFieldContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldContraseña.setToolTipText("");
        txtFieldContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldContraseñaFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 198;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 156, 0, 147);
        getContentPane().add(txtFieldContraseña, gridBagConstraints);

        btnComprobar.setText("COMPROBAR");
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 211, 20, 0);
        getContentPane().add(btnComprobar, gridBagConstraints);

        lblAvisoContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAvisoContraseña.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvisoContraseña.setText("         ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 85;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 156, 0, 147);
        getContentPane().add(lblAvisoContraseña, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        if(txtFieldContraseña.getText().equals("abc")){
            contraseñaCorrecta = true;
            lblAvisoContraseña.setText("Contraseña correcta");
            lblAvisoContraseña.setForeground(Color.BLACK);
            txtFieldContraseña.setEnabled(false);
            btnComprobar.setEnabled(false);
        }
        else{
            lblAvisoContraseña.setText("Contraseña incorrecta");
        }
    }//GEN-LAST:event_btnComprobarActionPerformed

    private void txtFieldContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldContraseñaFocusGained
        lblAvisoContraseña.setText("");
    }//GEN-LAST:event_txtFieldContraseñaFocusGained

    boolean getContraseñaCorrecta(){
        return contraseñaCorrecta;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DIALOG_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DIALOG_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DIALOG_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DIALOG_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DIALOG_Administrador dialog = new DIALOG_Administrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobar;
    private javax.swing.JLabel lblAvisoContraseña;
    private javax.swing.JLabel lblTextoBienvenida;
    private javax.swing.JTextField txtFieldContraseña;
    // End of variables declaration//GEN-END:variables
}
