/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marcovalderrey.mycompany.test_dgt;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author valde
 */
public class PANEL_Preguntas extends javax.swing.JPanel {

    ArrayList<Pregunta> listaDePreguntas = new ArrayList();
    ImageIcon Imagen;
    
    public PANEL_Preguntas() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblPregunta = new javax.swing.JLabel();
        lblOpcionA = new javax.swing.JLabel();
        lblOpcionB = new javax.swing.JLabel();
        lblOpcionC = new javax.swing.JLabel();
        lblOpcionD = new javax.swing.JLabel();
        lblPreguntaDebajo = new javax.swing.JLabel();
        lblOpcionDDebajo = new javax.swing.JLabel();
        lblOpcionADebajo = new javax.swing.JLabel();
        lblOpcionBDebajo = new javax.swing.JLabel();
        lblOpcionCDebajo = new javax.swing.JLabel();
        lblNumeroPregunta = new javax.swing.JLabel();
        btnOpcionA = new javax.swing.JToggleButton();
        btnOpcionB = new javax.swing.JToggleButton();
        btnOpcionC = new javax.swing.JToggleButton();
        btnOpcionD = new javax.swing.JToggleButton();
        panelImagen = new javax.swing.JPanel();
        Img = new javax.swing.JLabel();

        lblPregunta.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPregunta.setText("¿Esto es una pregunta de ejemplo para llenar el label y ver cuanto ocupa");

        lblOpcionA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcionA.setText("La primera fijo que no va a ser.");

        lblOpcionB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcionB.setText("Yo no se, a mí no me preguntes.");

        lblOpcionC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcionC.setText("Esta opción no parece demasiado fiable, es larga");

        lblOpcionD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcionD.setText("Da la casualidad de que esta opción es la correcta.");

        lblPreguntaDebajo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPreguntaDebajo.setText("mas o menos?");

        lblOpcionDDebajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblOpcionADebajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblOpcionBDebajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblOpcionCDebajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcionCDebajo.setText("y además no termina con punto");

        lblNumeroPregunta.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblNumeroPregunta.setText("1.");

        btnOpcionA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOpcionA.setText("A");
        btnOpcionA.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnOpcionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionAActionPerformed(evt);
            }
        });

        btnOpcionB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOpcionB.setText("B");
        btnOpcionB.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnOpcionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionBActionPerformed(evt);
            }
        });

        btnOpcionC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOpcionC.setText("C");
        btnOpcionC.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnOpcionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionCActionPerformed(evt);
            }
        });

        btnOpcionD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOpcionD.setText("D");
        btnOpcionD.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnOpcionD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Img, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Img, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPreguntaDebajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblNumeroPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOpcionADebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOpcionBDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOpcionD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOpcionCDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOpcionD, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOpcionDDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPregunta)
                    .addComponent(lblNumeroPregunta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreguntaDebajo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOpcionADebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnOpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblOpcionBDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblOpcionCDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOpcionD, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblOpcionDDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnOpcionD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionAActionPerformed
        quitarSeleccion();
        btnOpcionA.setSelected(true);
    }//GEN-LAST:event_btnOpcionAActionPerformed

    private void btnOpcionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionBActionPerformed
        quitarSeleccion();
        btnOpcionB.setSelected(true);
    }//GEN-LAST:event_btnOpcionBActionPerformed

    private void btnOpcionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionCActionPerformed
        quitarSeleccion();
        btnOpcionC.setSelected(true);
    }//GEN-LAST:event_btnOpcionCActionPerformed

    private void btnOpcionDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionDActionPerformed
        quitarSeleccion();
        btnOpcionD.setSelected(true);
    }//GEN-LAST:event_btnOpcionDActionPerformed

    void almacenarPreguntas(ArrayList<Pregunta> preguntas){
    
        for(int i = 0; i <preguntas.size(); i++){
            Pregunta pregunta = preguntas.get(i);
            pregunta.dividirCadenasLargas();
            listaDePreguntas.add(pregunta);
        }
        
    }
    
    void dividirCadenasLargasArrayList(){
    
        for(int i = 0; i < listaDePreguntas.size(); i++){
        
            listaDePreguntas.get(i).dividirCadenasLargas();
            
        }
        
    }
    
    void mostrarXPregunta(int indicePregunta){
        Pregunta pregunta = listaDePreguntas.get(indicePregunta);
        
        lblPregunta.setText(pregunta.getPregunta());
        lblPreguntaDebajo.setText(pregunta.getPreguntaAbajo());
        
        lblOpcionA.setText(pregunta.getRespuestaA());
        lblOpcionADebajo.setText(pregunta.getRespuestaAAbajo());
        
        lblOpcionB.setText(pregunta.getRespuestaB());
        lblOpcionBDebajo.setText(pregunta.getRespuestaBAbajo());
        
        lblOpcionC.setText(pregunta.getRespuestaC());
        lblOpcionCDebajo.setText(pregunta.getRespuestaCAbajo());
        
        lblOpcionD.setText(pregunta.getRespuestaD());
        lblOpcionDDebajo.setText(pregunta.getRespuestaDAbajo());
        
        anhadirImagen(pregunta.getImagen());
        
    }
    
    void setNumeroPregunta(String numero){
        lblNumeroPregunta.setText(numero);
    }
    
    void quitarSeleccion(){
        btnOpcionA.setSelected(false);
        btnOpcionB.setSelected(false);
        btnOpcionC.setSelected(false);
        btnOpcionD.setSelected(false);
    }
    
    void marcarOpcion(String opcion){
        
        switch (opcion) {
            case "A":
                btnOpcionA.setSelected(true);
                break;
            case "B":
                btnOpcionB.setSelected(true);
                break;
            case "C":
                btnOpcionC.setSelected(true);
                break;
            case "D":
                btnOpcionD.setSelected(true);
                break;
            default:
                break;
        }
        
    }
    
    String getOpcionSelecionada(){
        String opcion = "Ninguna";
        
        if(btnOpcionA.isSelected()){opcion = "A";}
        else if(btnOpcionB.isSelected()){opcion = "B";}
        else if(btnOpcionC.isSelected()){opcion = "C";}
        else if(btnOpcionD.isSelected()){opcion = "D";}
        
        return opcion;
    }
    
    Pregunta desordenarRespuestas(Pregunta pregunta){
    
        Random r = new Random();
        String respuestas[] = {pregunta.getRespuestaA(), pregunta.getRespuestaB(), pregunta.getRespuestaC(), pregunta.getRespuestaD()};
        
        // 1º método: posición aleatoria
        for (int i=0; i<respuestas.length; i++) {
            int posAleatoria = r.nextInt(respuestas.length);
            String temp = respuestas[i];
            respuestas[i] = respuestas[posAleatoria];
            respuestas[posAleatoria] = temp;
        }
 
        // 2º método: Collection.shuffle
        List<String> lista = Arrays.asList(respuestas);
        Collections.shuffle(lista);
 
        lista.toArray(respuestas);
        
        Pregunta preguntaDesordenada = new Pregunta(pregunta.getPregunta(), respuestas[0], respuestas[1], respuestas[2], respuestas[3], pregunta.getRespuestaCorrecta(), pregunta.getImagen());
        
        return preguntaDesordenada;
        
    }
    
    
    void anhadirImagen(String imagen){
    
        Imagen = new ImageIcon("imagenes\\" + imagen);
        Img.setIcon(Imagen);
    
    }
    
    ArrayList<Pregunta> getListaPreguntas(){return listaDePreguntas;}
    void setListaPreguntas(ArrayList<Pregunta> listaPreguntas){listaDePreguntas = listaPreguntas;}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Img;
    private javax.swing.JToggleButton btnOpcionA;
    private javax.swing.JToggleButton btnOpcionB;
    private javax.swing.JToggleButton btnOpcionC;
    private javax.swing.JToggleButton btnOpcionD;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblNumeroPregunta;
    private javax.swing.JLabel lblOpcionA;
    private javax.swing.JLabel lblOpcionADebajo;
    private javax.swing.JLabel lblOpcionB;
    private javax.swing.JLabel lblOpcionBDebajo;
    private javax.swing.JLabel lblOpcionC;
    private javax.swing.JLabel lblOpcionCDebajo;
    private javax.swing.JLabel lblOpcionD;
    private javax.swing.JLabel lblOpcionDDebajo;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblPreguntaDebajo;
    private javax.swing.JPanel panelImagen;
    // End of variables declaration//GEN-END:variables
}
