/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marcovalderrey.mycompany.test_dgt;

/**
 *
 * @author valde
 */
public class PANEL_Resultados extends javax.swing.JPanel {

    /**
     * Creates new form PANEL_Resultados
     */
    public PANEL_Resultados() {
        initComponents();
    }

    void rellenarCampos(String nombreYApellidos, String dni, String tipoTest, String numPreguntas){
    
        beanResultados.setLblNombreARellenar(nombreYApellidos);
        beanResultados.setLblDNIARellenar(dni);
        beanResultados.setLblTipoTestARellenar(tipoTest);
        beanResultados.setLblNumPreguntasARellenar(numPreguntas);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextoBienvenida = new javax.swing.JLabel();
        beanResultados = new com.marcovalderrey.mycompany.test_dgt.BEAN_ResultadosTest();

        lblTextoBienvenida.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTextoBienvenida.setText("Resultados del test");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(lblTextoBienvenida)
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beanResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(beanResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.marcovalderrey.mycompany.test_dgt.BEAN_ResultadosTest beanResultados;
    private javax.swing.JLabel lblTextoBienvenida;
    // End of variables declaration//GEN-END:variables
}
