/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.test_dgt;

import java.util.ArrayList;

/**
 *
 * @author valde
 */
public class PANEL_Preguntas extends javax.swing.JPanel {

    ArrayList<Pregunta> listaDePreguntas = new ArrayList();
    
    public PANEL_Preguntas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblPregunta = new javax.swing.JLabel();
        btnOpcionA = new javax.swing.JButton();
        btnOpcionB = new javax.swing.JButton();
        btnOpcionC = new javax.swing.JButton();
        btnOpcionD = new javax.swing.JButton();
        lblOpcionA = new javax.swing.JLabel();
        lblOpcionB = new javax.swing.JLabel();
        lblOpcionC = new javax.swing.JLabel();
        lblOpcionD = new javax.swing.JLabel();
        lblPreguntaDebajo = new javax.swing.JLabel();
        lblOpcionDDebajo = new javax.swing.JLabel();
        lblOpcionADebajo = new javax.swing.JLabel();
        lblOpcionBDebajo = new javax.swing.JLabel();
        lblOpcionCDebajo = new javax.swing.JLabel();

        lblPregunta.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPregunta.setText("¿Esto es una pregunta de ejemplo para llenar el label y ver cuanto ocupa");

        btnOpcionA.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnOpcionA.setText("A");
        btnOpcionA.setMargin(new java.awt.Insets(8, 12, 8, 12));

        btnOpcionB.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnOpcionB.setText("B");
        btnOpcionB.setMargin(new java.awt.Insets(8, 12, 8, 12));

        btnOpcionC.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnOpcionC.setText("C");
        btnOpcionC.setMargin(new java.awt.Insets(8, 12, 8, 12));

        btnOpcionD.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnOpcionD.setText("D");
        btnOpcionD.setMargin(new java.awt.Insets(8, 12, 8, 12));

        lblOpcionA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcionA.setText("La primera fijo que no va a ser.");

        lblOpcionB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcionB.setText("Yo no se, a mí no me preguntes.");

        lblOpcionC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcionC.setText("Esta opción no parece demasiado fiable, es larga");

        lblOpcionD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcionD.setText("Da la casualidad de que esta opción es la correcta.");

        lblPreguntaDebajo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblPreguntaDebajo.setText("mas o menos?");

        lblOpcionDDebajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblOpcionADebajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblOpcionBDebajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblOpcionCDebajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpcionCDebajo.setText("y además no termina con punto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpcionD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOpcionD, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOpcionDDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOpcionCDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOpcionBDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOpcionADebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreguntaDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreguntaDebajo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOpcionA, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOpcionADebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOpcionBDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOpcionCDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpcionD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOpcionD, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOpcionDDebajo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    void almacenarPreguntas(ArrayList<Pregunta> preguntas){
    
        for(int i = 0; i <preguntas.size(); i++){
            Pregunta pregunta = preguntas.get(i);
            pregunta.dividirCadenasLargas();
            listaDePreguntas.add(pregunta);
        }
        
    }
    
    void dividirCadenasLargasArrayList(){
    
        for(int i = 0; i < listaDePreguntas.size(); i++){
        
            listaDePreguntas.get(i).dividirCadenasLargas();
            
        }
        
    }
    
    void mostrarPrimeraPregunta(){
        Pregunta primeraPregunta = listaDePreguntas.get(0);
        
        lblPregunta.setText(primeraPregunta.getPregunta());
        lblPreguntaDebajo.setText(primeraPregunta.getPreguntaAbajo());
        System.out.println(lblPregunta.getText());
        System.out.println(lblPreguntaDebajo.getText());
        lblOpcionA.setText(primeraPregunta.getRespuestaA());
        lblOpcionADebajo.setText(primeraPregunta.getRespuestaAAbajo());
        System.out.println(lblOpcionA.getText());
        System.out.println(lblOpcionADebajo.getText());
        lblOpcionB.setText(primeraPregunta.getRespuestaB());
        lblOpcionBDebajo.setText(primeraPregunta.getRespuestaBAbajo());
        
        lblOpcionC.setText(primeraPregunta.getRespuestaC());
        lblOpcionCDebajo.setText(primeraPregunta.getRespuestaCAbajo());
        
        lblOpcionD.setText(primeraPregunta.getRespuestaD());
        lblOpcionDDebajo.setText(primeraPregunta.getRespuestaDAbajo());
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpcionA;
    private javax.swing.JButton btnOpcionB;
    private javax.swing.JButton btnOpcionC;
    private javax.swing.JButton btnOpcionD;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblOpcionA;
    private javax.swing.JLabel lblOpcionADebajo;
    private javax.swing.JLabel lblOpcionB;
    private javax.swing.JLabel lblOpcionBDebajo;
    private javax.swing.JLabel lblOpcionC;
    private javax.swing.JLabel lblOpcionCDebajo;
    private javax.swing.JLabel lblOpcionD;
    private javax.swing.JLabel lblOpcionDDebajo;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblPreguntaDebajo;
    // End of variables declaration//GEN-END:variables
}
