/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.test_dgt;

/**
 *
 * @author valde
 */
public class PANEL_Principal extends javax.swing.JPanel {

    /**
     * Creates new form PANEL_Principal
     */
    public PANEL_Principal() {
        initComponents();
    }

    boolean comprobarContenidoCampos(){
        boolean campoVacio = false;
        beanDatosPersonales.setNombre();
        String nombre = beanDatosPersonales.getNombre();
        beanDatosPersonales.setApellidos();
        String apellidos = beanDatosPersonales.getApellidos();
        beanDatosPersonales.setDni();
        String dni = beanDatosPersonales.getDni();
        if(nombre.equals("") | apellidos.equals("") | dni.equals("")){
            campoVacio = true;
        }
        return campoVacio;
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beanDatosPersonales = new com.mycompany.test_dgt.BEAN_Datos_Personales();
        beanCaracteristicasTest = new com.mycompany.test_dgt.BEAN_Caracteristicas_Test();
        lblTextoBienvenida = new javax.swing.JLabel();

        beanCaracteristicasTest.setEnabled(false);
        beanCaracteristicasTest.setFocusable(false);

        lblTextoBienvenida.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTextoBienvenida.setText("¡Bienvenido al test de la DGT!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(beanDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beanCaracteristicasTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblTextoBienvenida)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTextoBienvenida)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(beanCaracteristicasTest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beanDatosPersonales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.test_dgt.BEAN_Caracteristicas_Test beanCaracteristicasTest;
    private com.mycompany.test_dgt.BEAN_Datos_Personales beanDatosPersonales;
    private javax.swing.JLabel lblTextoBienvenida;
    // End of variables declaration//GEN-END:variables
}
